eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

USER_SERVICE_URL=http://users-service
POSTS_SERVICE_URL=http://posts-service
NOTIFICATION_SERVICE_URL=http://notifications-service
CONNECTIONS_SERVICE_URL=http://connections-service

management.endpoints.web.exposure.include=health
