spring.application.name=uploads-service
server.port=8888
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

server.servlet.context-path=/uploads

cloudinary.cloud-name=djkxs4ogm
cloudinary.cloud-api-key=566545996795134
cloudinary.cloud-api-secret=pyBcewZmX8wCBNTvqeWaTfZNSjo