spring.application.name=notifications-service

#no use of localhost docker container service name
spring.datasource.url=jdbc:postgresql://${DB_SERVICE:notification-db}:5432/${DB_DATABASE:notificationservice}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
server.port=1111
# Hibernate properties (if using Spring Data JPA)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# Optional: Logging SQL statements
spring.jpa.show-sql=true


jwt.secret.key = fsjngfjdfngksndfjsbndgkjnsdfbskjgbsjfksjbgkjsnfgkjsbngkkbkgdbkbgdfgkjfbgkjdfbgkjdbgkjs
#no use of localhost docker container service name
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
