spring.application.name=connections-service

server.servlet.context-path=/connections
server.port=9030

# ? Correct property name for Eureka
#no use of localhost docker container service name
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

# ? Neo4j connection settings
#no use of localhost docker container service name
spring.neo4j.uri=bolt://connection-db:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=12345678
