eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

USERS_SERVICE_URL=http://users-service
POSTS_SERVICE_URL=http://posts-service
NOTIFICATIONS_SERVICE_URL=http://notifications-service
CONNECTIONS_SERVICE_URL=http://connections-service